# Generated by Django 5.0.4 on 2024-07-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=25)),
                ('doc_image', models.ImageField(upload_to='doctors/')),
                ('fb_url', models.URLField(max_length=255)),
                ('twitter_url', models.URLField(max_length=255)),
                ('insta_url', models.URLField(max_length=255)),
                ('doc_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department')),
            ],
        ),
    ]
