# Generated by Django 5.0.4 on 2024-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=35)),
                ('subject', models.TextField()),
                ('msg', models.CharField(max_length=350)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor_dep',
            name='doc_dep',
        ),
        migrations.DeleteModel(
            name='msg',
        ),
        migrations.DeleteModel(
            name='Doctor_dep',
        ),
    ]
