# Generated by Django 5.0.4 on 2024-07-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_contact_remove_doctor_dep_doc_dep_delete_msg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='Phone',
            field=models.IntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
