# Generated by Django 5.0.4 on 2024-07-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_contact_subject_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='msg',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default=0, max_length=350),
            preserve_default=False,
        ),
    ]
