# Generated by Django 5.0.4 on 2024-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_contact_msg_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
