# Generated by Django 5.0.4 on 2024-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_contact_phone_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=350),
        ),
        migrations.AddField(
            model_name='contact',
            name='Phone',
            field=models.IntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
