# Generated by Django 5.0.4 on 2024-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
