# Generated by Django 5.0.4 on 2024-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
