# Generated by Django 5.0.4 on 2024-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
