# Generated by Django 5.0.4 on 2024-07-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_sp_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardiology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('fb', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('instagram', models.URLField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Sp_Doctor',
        ),
    ]
