# Generated by Django 5.0.4 on 2024-07-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_cardiology_delete_sp_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiology',
            name='department',
        ),
    ]
