# Generated by Django 5.0.4 on 2024-08-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_remove_cardiology_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('speciality', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Cardiology',
        ),
    ]
