# Generated by Django 5.0.4 on 2024-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_doctor1_delete_cardiology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('speciality', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('fb', models.URLField(max_length=150)),
                ('twitter', models.URLField(max_length=150)),
                ('instagram', models.URLField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor1',
        ),
    ]
