# Generated by Django 5.0.4 on 2024-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_doctor1_delete_special_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('speciality', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='cardiologist/')),
                ('fb', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('instagram', models.URLField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor1',
        ),
    ]
