# Generated by Django 5.0.4 on 2024-08-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_specialist_delete_doctor1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialist',
            new_name='Doctor1',
        ),
    ]
