# Generated by Django 5.0.4 on 2024-08-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_rename_specialist_doctor1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor1',
            name='image',
            field=models.ImageField(upload_to='doctors/'),
        ),
    ]
